/**
 * Fills two empty fields from data we already hold, before reaching for any
 * external source:
 *
 *  - certifications: parsed out of the "Standards/Approvals" and "Hazardous
 *    Area Certification" specs, which 962 products already carry. The field
 *    was 100% empty purely because the importer never mapped it.
 *
 *  - description: composed from the product's own specifications. Deliberately
 *    factual and generated by us — the source file's description column is the
 *    retailer's marketing copy and was excluded on import for that reason.
 *
 * Run: npx tsx scripts/derive-from-specs.ts [--commit]
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const COMMIT = process.argv.includes("--commit");

// Marks worth surfacing as a badge. Ordered so the output reads consistently.
const MARKS = [
  "CE", "UKCA", "UL", "cULus", "cUL", "CSA", "RoHS", "REACH", "WEEE",
  "ATEX", "IECEx", "EAC", "CCC", "KC", "RCM", "VDE", "TUV", "FM",
  "DNV", "ABS", "LR", "BV",
];

function extractCertifications(values: string[]): string[] {
  const found = new Set<string>();
  for (const raw of values) {
    for (const mark of MARKS) {
      // Bounded match so "UL" doesn't fire inside "MODULE" or "CULus".
      const re = new RegExp(`(^|[^A-Za-z0-9])${mark}([^A-Za-z0-9]|$)`);
      if (re.test(raw)) found.add(mark);
    }
  }
  // cULus implies UL listing; keep the more specific mark only.
  if (found.has("cULus")) found.delete("cUL");
  return MARKS.filter((m) => found.has(m));
}

/** Human-readable sentence from the specs that matter most for this part. */
function buildDescription(
  name: string,
  brand: string,
  categoryName: string,
  specs: { key: string; name: string; value: string; unit: string | null }[]
): string {
  const get = (k: string) => specs.find((s) => s.key === k)?.value;

  const productType = get("product_type");
  const series = get("series");

  const lead = productType
    ? `${brand} ${productType}${series ? ` from the ${series} series` : ""}.`
    : `${brand} ${categoryName.toLowerCase()} part.`;

  // Pick the specs an engineer actually selects on, in a sensible order.
  const HIGHLIGHT: [string, string][] = [
    ["voltage", "supply"],
    ["coil_voltage", "coil"],
    ["current", "rated current"],
    ["power_w", "power"],
    ["ip_rating", "protection"],
    ["contacts", "contacts"],
    ["poles", "poles"],
    ["channels", "channels"],
    ["communication", "communication"],
    ["output_type", "output"],
    ["mounting", "mounting"],
    ["terminal_type", "terminals"],
    ["bore", "bore"],
    ["stroke", "stroke"],
  ];

  const parts: string[] = [];
  for (const [key, label] of HIGHLIGHT) {
    const v = get(key);
    if (!v) continue;
    const unit = specs.find((s) => s.key === key)?.unit;
    parts.push(`${label} ${v}${unit && !v.includes(unit) ? ` ${unit}` : ""}`);
    if (parts.length === 5) break;
  }

  const specSentence = parts.length ? ` Key ratings: ${parts.join(", ")}.` : "";

  const minT = get("minimum_operating_temperature");
  const maxT = get("maximum_operating_temperature");
  const tempSentence = minT && maxT ? ` Operating range ${minT} to ${maxT}.` : "";

  return `${lead}${specSentence}${tempSentence} Supplied by AutoParts MENA for industrial customers across Egypt, the Middle East and Africa.`
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  const products = await prisma.product.findMany({
    include: {
      brand: { select: { name: true } },
      category: { select: { name: true } },
      specs: { select: { specKey: true, specName: true, value: true, unit: true } },
    },
  });

  let certsSet = 0, descSet = 0, certMarksTotal = 0;
  const sample: string[] = [];

  for (const p of products) {
    const approvalValues = p.specs
      .filter((s) => /standards|approval|certification|hazardous/i.test(s.specName))
      .map((s) => s.value);

    const certs = extractCertifications(approvalValues);

    const description = buildDescription(
      p.name,
      p.brand.name,
      p.category.name,
      p.specs.map((s) => ({ key: s.specKey, name: s.specName, value: s.value, unit: s.unit }))
    );

    const data: { certifications?: string; description?: string } = {};
    if (certs.length) { data.certifications = JSON.stringify(certs); certsSet++; certMarksTotal += certs.length; }
    if (description) { data.description = description; descSet++; }

    if (sample.length < 3 && certs.length) {
      sample.push(`${p.sku}\n    certs: ${certs.join(", ")}\n    desc : ${description.slice(0, 170)}…`);
    }

    if (COMMIT && Object.keys(data).length) {
      await prisma.product.update({ where: { id: p.id }, data });
    }
  }

  console.log(`products                 : ${products.length}`);
  console.log(`certifications populated : ${certsSet} (${Math.round((certsSet / products.length) * 100)}%)`);
  console.log(`avg marks per product    : ${(certMarksTotal / Math.max(certsSet, 1)).toFixed(1)}`);
  console.log(`descriptions written     : ${descSet} (${Math.round((descSet / products.length) * 100)}%)`);
  console.log("\nsamples:");
  for (const s of sample) console.log("  ", s);
  console.log(COMMIT ? "\nApplied." : "\nDRY RUN — re-run with --commit.");
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
