/**
 * Dumps the local SQLite catalogue to a SQL file that `wrangler d1 execute`
 * can load into D1.
 *
 * The alternative was pointing the seed and import scripts at D1 directly, but
 * D1 is a Worker binding rather than a connection string — there is nothing
 * for a Node script to connect to. So the catalogue is built locally with the
 * existing pipeline, verified there, and shipped as SQL.
 *
 * Values are escaped and emitted as literals rather than parameters, because
 * the target is a plain .sql file. Everything written here comes from our own
 * database, not from user input.
 *
 * Run: npx tsx scripts/dump-for-d1.ts
 * Then: npx wrangler d1 execute nexumotion --remote --file=./d1-seed.sql
 */
import { PrismaClient } from "@prisma/client";
import { writeFileSync, readFileSync, existsSync } from "fs";

const prisma = new PrismaClient();
const OUT = "d1-seed.sql";
const SCHEMA = "prisma/d1-schema.sql";

// Parents before children: D1 enforces foreign keys, so a child row inserted
// before its parent is rejected.
const TABLES = [
  "User",
  "Brand",
  "Category",
  "SpecTemplate",
  "Product",
  "ProductSpec",
  "CrossReference",
  "PriceTier",
  "Project",
  "ProjectItem",
  "QuoteRequest",
  "QuoteItem",
  "Order",
  "OrderItem",
  "Review",
  "SavedSearch",
  "Inquiry",
];

function literal(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "bigint") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  if (v instanceof Date) return `'${v.toISOString()}'`;
  if (Buffer.isBuffer(v)) return `X'${v.toString("hex")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  if (!existsSync(SCHEMA)) {
    console.error(`Missing ${SCHEMA}. Generate it with:
  npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > ${SCHEMA}`);
    process.exit(1);
  }

  const parts: string[] = [];
  parts.push("-- NexuMotion catalogue, generated by scripts/dump-for-d1.ts");
  parts.push("-- Load with: npx wrangler d1 execute nexumotion --remote --file=./d1-seed.sql\n");
  parts.push(readFileSync(SCHEMA, "utf8"));
  parts.push("\n-- Data\n");

  let totalRows = 0;

  for (const table of TABLES) {
    const rows = (await prisma.$queryRawUnsafe(
      `SELECT * FROM "${table}"`
    )) as Record<string, unknown>[];
    if (!rows.length) {
      console.log(`  ${table.padEnd(16)} 0`);
      continue;
    }

    const cols = Object.keys(rows[0]);
    const colList = cols.map((c) => `"${c}"`).join(", ");

    // Batched multi-row inserts: one statement per row would make the file
    // enormous and the load slow, and D1 caps how many statements it will take.
    const CHUNK = 200;
    for (let i = 0; i < rows.length; i += CHUNK) {
      const values = rows
        .slice(i, i + CHUNK)
        .map((r) => `(${cols.map((c) => literal(r[c])).join(", ")})`)
        .join(",\n  ");
      parts.push(`INSERT INTO "${table}" (${colList}) VALUES\n  ${values};\n`);
    }

    totalRows += rows.length;
    console.log(`  ${table.padEnd(16)} ${rows.length}`);
  }

  const sql = parts.join("\n");
  writeFileSync(OUT, sql, "utf8");
  console.log(`\n  ${totalRows.toLocaleString()} rows -> ${OUT} (${(Buffer.byteLength(sql) / 1024 / 1024).toFixed(2)} MB)`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(String(e).slice(0, 500));
    process.exit(1);
  });
