export const brands = [
  { name: "Siemens", country: "Germany", description: "Global leader in industrial automation — SIMATIC PLCs, SINAMICS drives, and factory digitalization." },
  { name: "Schneider Electric", country: "France", description: "Energy management and automation — Modicon PLCs, Altivar drives, TeSys motor control." },
  { name: "ABB", country: "Switzerland", description: "Robotics, drives, and electrification — ACS drives, AC500 PLCs, industrial robots." },
  { name: "Delta", country: "Taiwan", description: "Cost-effective automation — VFD drives, DVP PLCs, HMIs, and servo systems." },
  { name: "Allen-Bradley", country: "USA", description: "Rockwell Automation brand — ControlLogix, CompactLogix, PowerFlex drives." },
  { name: "Omron", country: "Japan", description: "Sensing and control — NX/NJ controllers, E3 photoelectric sensors, safety." },
  { name: "Mitsubishi Electric", country: "Japan", description: "MELSEC PLCs, FR inverters, MELSERVO servo systems." },
  { name: "Honeywell", country: "USA", description: "Process automation, DCS systems, and field instrumentation." },
  { name: "Emerson", country: "USA", description: "Process control — DeltaV DCS, Rosemount instruments, ASCO valves." },
  { name: "Yokogawa", country: "Japan", description: "Process instrumentation and DCS — CENTUM, EJA transmitters." },
  { name: "Danfoss", country: "Denmark", description: "VLT and VACON drives, hydraulics, and refrigeration controls." },
  { name: "INVT", country: "China", description: "Value-line VFDs, servo drives, PLCs, and elevator controls." },
  { name: "Fuji Electric", country: "Japan", description: "FRENIC drives, contactors, and power semiconductors." },
  { name: "Yaskawa", country: "Japan", description: "Sigma servo systems, GA/A1000 drives, Motoman robots." },
  { name: "LS Electric", country: "South Korea", description: "XGT PLCs, iS7/M100 drives, Metasol contactors." },
  { name: "Fanuc", country: "Japan", description: "CNC systems, industrial robots, and factory automation." },
  { name: "KUKA", country: "Germany", description: "Industrial robots and automated production systems." },
  { name: "Bosch Rexroth", country: "Germany", description: "Drive and control — hydraulics, electric drives, linear motion." },
  { name: "Beckhoff", country: "Germany", description: "PC-based control — TwinCAT, EtherCAT terminals, IPCs." },
  { name: "B&R", country: "Austria", description: "ABB Industrial Automation — X20 I/O, Automation PC, ACOPOS." },
  { name: "Endress+Hauser", country: "Switzerland", description: "Process instrumentation — flow, level, pressure, analytics." },
  { name: "IFM Electronic", country: "Germany", description: "Position sensors, IO-Link masters, and condition monitoring." },
  { name: "WAGO", country: "Germany", description: "Terminal blocks, I/O systems, and interface electronics." },
  { name: "Pepperl+Fuchs", country: "Germany", description: "Sensors and explosion protection — proximity, ultrasonic, IS barriers." },
  { name: "SEW-Eurodrive", country: "Germany", description: "Gearmotors, frequency inverters, and decentralized drives." },
  { name: "Banner Engineering", country: "USA", description: "Photoelectric sensors, LED lighting, and wireless solutions." },
  { name: "SICK", country: "Germany", description: "Sensor intelligence — safety scanners, encoders, vision." },
  { name: "Balluff", country: "Germany", description: "Sensors, RFID systems, and connectivity." },
  { name: "Turck", country: "Germany", description: "Sensors, fieldbus technology, and connectivity." },
  { name: "Phoenix Contact", country: "Germany", description: "Terminal blocks, power supplies, relays, and connectors." },
  { name: "Pilz", country: "Germany", description: "Safe automation — PNOZ safety relays, PSS controllers." },
  { name: "Festo", country: "Germany", description: "Pneumatic and electric automation — cylinders, valves, terminals." },
  { name: "SMC", country: "Japan", description: "Pneumatic components — cylinders, valves, air preparation." },
  { name: "Weintek", country: "Taiwan", description: "cMT and MT-series HMIs with EasyBuilder software." },
  { name: "Inovance", country: "China", description: "MD-series drives, servo systems, and machine controllers." },
  { name: "Kinco", country: "China", description: "HMIs, steppers, servo systems, and PLCs." },
  { name: "Pro-face", country: "Japan", description: "Schneider brand — GP/SP series industrial HMIs." },
  { name: "Advantech", country: "Taiwan", description: "Industrial PCs, panel PCs, and IoT gateways." },
  { name: "Red Lion", country: "USA", description: "Panel meters, protocol converters, and industrial networking." },
  { name: "Maple Systems", country: "USA", description: "HMIs and operator interface panels." },
  { name: "Beijer Electronics", country: "Sweden", description: "X2 HMIs and Westermo industrial networking." },
  { name: "Xinje", country: "China", description: "XD/XL PLCs, TG HMIs, and DS servo drives." },
  { name: "Hanyoung Nux", country: "South Korea", description: "Temperature controllers, counters, timers, and sensors." },
  { name: "Autonics", country: "South Korea", description: "Sensors, controllers, and motion devices." },
  { name: "Carlo Gavazzi", country: "Switzerland", description: "Solid state relays, energy meters, and monitoring relays." },
  { name: "Finder", country: "Italy", description: "Relays, timers, and surge protection devices." },
  { name: "Lovato", country: "Italy", description: "Motor protection, contactors, and automatic transfer switches." },
  { name: "Crouzet", country: "France", description: "Micro motors, control relays, and switches." },
  { name: "Crydom", country: "USA", description: "Solid state relays and contactors." },
  { name: "Panasonic Industry", country: "Japan", description: "Sensors, relays, PLCs, and servo systems." },
];
